server.port: 80

spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/yt_college?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  #实体类所做包
  type-aliases-package: com.zyt.ytcollege.dao.DO,com.zyt.ytcollege.service.DTO
  #mapper.xml所在位置
  mapper-locations: classpath:com/zyt/ytcollege/dao/mapper/*.xml
  # 开启驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql

logging:
  config: classpath:logback.xml
  level:
    com:
      zyt:
        ytcollege:
          dao:
            mapper: debug